### ISSUE TITLE
CircleCI: Curious if we can use Ruby Orb

### ISSUE THREAD

**Issue by olleolleolle** [mattbrictson/pgcli-rails#41]
Would it be possible to make use of the Ruby Orb, to compact the CI configuration a bit?

https://circleci.com/developer/orbs/orb/circleci/ruby#usage-examples

**Comment by mattbrictson** [comment]
Good question. Last time I checked, the CircleCI Ruby orb is tuned for apps, not gems. For example, if I am not mistaken, the bundler cache won't work unless the project has a `Gemfile.lock` checked into source control. This is the case for e.g. Rails apps, but generally speaking for gem development you do not commit the lock file.
